# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_pinout.xdc

# Block Designs: bd/snkrddl_blk_0/snkrddl_blk_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snkrddl_blk_0 || ORIG_REF_NAME==snkrddl_blk_0} -quiet] -quiet

# IP: bd/snkrddl_blk_0/ip/snkrddl_blk_0_processing_system7_0_0/snkrddl_blk_0_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snkrddl_blk_0_processing_system7_0_0 || ORIG_REF_NAME==snkrddl_blk_0_processing_system7_0_0} -quiet] -quiet

# IP: bd/snkrddl_blk_0/ip/snkrddl_blk_0_gmii_to_rgmii_0_0/snkrddl_blk_0_gmii_to_rgmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snkrddl_blk_0_gmii_to_rgmii_0_0 || ORIG_REF_NAME==snkrddl_blk_0_gmii_to_rgmii_0_0} -quiet] -quiet

# IP: bd/snkrddl_blk_0/ip/snkrddl_blk_0_gmii_to_rgmii_1_0/snkrddl_blk_0_gmii_to_rgmii_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snkrddl_blk_0_gmii_to_rgmii_1_0 || ORIG_REF_NAME==snkrddl_blk_0_gmii_to_rgmii_1_0} -quiet] -quiet

# IP: bd/snkrddl_blk_0/ip/snkrddl_blk_0_proc_sys_reset_0_0/snkrddl_blk_0_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snkrddl_blk_0_proc_sys_reset_0_0 || ORIG_REF_NAME==snkrddl_blk_0_proc_sys_reset_0_0} -quiet] -quiet

# XDC: bd/snkrddl_blk_0/snkrddl_blk_0_ooc.xdc
