# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/parallels/snkrddl_blk_0/snkrddl_blk_0.srcs/sources_1/bd/snkrddl_blk_0/ip/snkrddl_blk_0_processing_system7_0_0/snkrddl_blk_0_processing_system7_0_0.xci
# IP: The module: 'snkrddl_blk_0_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/snkrddl_blk_0/snkrddl_blk_0.srcs/sources_1/bd/snkrddl_blk_0/ip/snkrddl_blk_0_processing_system7_0_0/snkrddl_blk_0_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'snkrddl_blk_0_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/parallels/snkrddl_blk_0/snkrddl_blk_0.srcs/sources_1/bd/snkrddl_blk_0/ip/snkrddl_blk_0_processing_system7_0_0/snkrddl_blk_0_processing_system7_0_0.xci
# IP: The module: 'snkrddl_blk_0_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/snkrddl_blk_0/snkrddl_blk_0.srcs/sources_1/bd/snkrddl_blk_0/ip/snkrddl_blk_0_processing_system7_0_0/snkrddl_blk_0_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'snkrddl_blk_0_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
